### ISSUE TITLE
Crashes when attempting to find game

### ISSUE THREAD

**Issue by thisisauser9** [ReHamster/UPlayEmulator#1]
Whenever I attempt to find a multiplayer game, I crash, I've tried reinstalling the game, deleting my profile in my documents, etc and I still crash, however I can still play if I join a friend and then he finds a match.

**Comment by SoapyMan** [comment]
Since it is not a custom game server and this particular project is relies on Ubisoft servers connection - that could be one of the game problems itself. 
DSF PC has plenty of bugs (such as friends list overflow crash, connectivity issues between players) which were not fixed properly by the Ubi Kiev devs back then.

**Comment by thisisauser9** [comment]
Ok so what do you recommend I do to fix the issue? I am connected to a VPN basically at all times, I will try go online with it off and tell you if it lets me connect
Edit: VPN being off didn't fix anything, also I forgot to mention this used to work a while ago without any crashing

**Comment by thisisauser9** [comment]
Snoopii helped me fix it nvm

How to fix if somebody is having this issue in the future:
Try disabling unused Virtual network adaptors and repeat until it works
